import { TECHS, TERRAIN, UNIT_TYPES } from "../content/config.js";
import { indexOf, neighbors, distance, reveal } from "./world.js";

export function settlementYield(state, settlement) {
  const positions=[{x:settlement.x,y:settlement.y},...neighbors(state,settlement).slice(0,3)];
  const total={food:0,production:0,science:0};
  for(const p of positions){const y=TERRAIN[state.map.tiles[indexOf(p.x,p.y,state.map.width)].terrain].yield;for(const k of Object.keys(total))total[k]+=y[k];}
  total.food+=settlement.population+(state.research.completed.includes("agriculture")?1:0);
  total.science+=2;
  total.production+=state.research.completed.includes("masonry")?1:0; return total;
}
export function chooseResearch(state,id){if(!TECHS[id]||state.research.completed.includes(id))return {ok:false,reason:"Недоступное исследование."};const t=TECHS[id];if(t.requires&&!state.research.completed.includes(t.requires))return {ok:false,reason:"Сначала нужно предыдущее знание."};state.research.active=id;state.research.progress=0;return {ok:true};}
export function foundSettlement(state,unitId){const unit=state.units.find(u=>u.id===unitId);if(!unit||unit.type!=="settler")return {ok:false,reason:"Нужен отряд поселенцев."};if(state.settlements.some(s=>distance(s,unit)<4))return {ok:false,reason:"Слишком близко к другому поселению."};const tile=state.map.tiles[indexOf(unit.x,unit.y,state.map.width)];if(!TERRAIN[tile.terrain].passable)return {ok:false,reason:"Здесь нельзя основать поселение."};state.settlements.push({id:`s-${state.turn}-${unit.x}`,name:"Новый Рубеж",x:unit.x,y:unit.y,population:1,development:0});state.units=state.units.filter(u=>u.id!==unitId);state.selectedUnitId=state.units.find(u=>u.owner==="player")?.id??null;state.log.unshift("Основан Новый Рубеж.");return {ok:true};}
function aiTurn(state){const ai=state.units.filter(u=>u.owner==="ai");const target=state.settlements[0];for(const unit of ai){const options=neighbors(state,unit).filter(p=>TERRAIN[state.map.tiles[indexOf(p.x,p.y,state.map.width)].terrain].passable&&!state.units.some(o=>o.id!==unit.id&&o.x===p.x&&o.y===p.y));options.sort((a,b)=>distance(a,target)-distance(b,target)||a.y-b.y||a.x-b.x);if(options[0]){unit.x=options[0].x;unit.y=options[0].y;}if(state.map.tiles[indexOf(unit.x,unit.y,state.map.width)].revealed)state.log.unshift("Замечено движение степных налётчиков.");}}
export function endTurn(state){if(state.phase!=="player")return {ok:false,reason:"Ход уже разрешается."};state.phase="world";const income={food:0,production:0,science:0};for(const s of state.settlements){const y=settlementYield(state,s);for(const k of Object.keys(income))income[k]+=y[k];s.development++;if(s.development%4===0){s.population++;state.log.unshift(`${s.name}: население выросло до ${s.population}.`);}}for(const k of Object.keys(income))state.resources[k]+=income[k];if(state.research.active){state.research.progress+=income.science;const tech=TECHS[state.research.active];if(state.research.progress>=tech.cost){state.research.completed.push(state.research.active);state.log.unshift(`Открыто: ${tech.name}. Доступно: ${tech.unlock}.`);state.research.active=null;state.research.progress=0;}}aiTurn(state);state.turn++;for(const u of state.units)u.movement=UNIT_TYPES[u.type].movement;for(const u of state.units.filter(u=>u.owner==="player"))reveal(state,u,UNIT_TYPES[u.type].vision);state.phase="player";state.log.unshift(`Ход ${state.turn}. Получено: ${income.food} пищи, ${income.production} производства, ${income.science} знаний.`);return {ok:true,income};}
export function era(state){if(state.research.completed.includes("masonry"))return "Город";if(state.research.completed.length||state.settlements.some(s=>s.population>=2))return "Поселение";return "Племя";}
