import { TERRAIN, UNIT_TYPES } from "../content/config.js";
import { indexOf } from "../domain/world.js";
const TILE=56;
export class MapView {
  constructor(canvas,camera,onTile,onUnit){this.canvas=canvas;this.ctx=canvas.getContext("2d");this.camera=camera;this.onTile=onTile;this.onUnit=onUnit;this.wasDrag=false;this.bind();}
  resize(){const rect=this.canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;this.canvas.width=rect.width*dpr;this.canvas.height=rect.height*dpr;this.ctx.setTransform(dpr,0,0,dpr,0,0);}
  bind(){let start=null;this.canvas.addEventListener("pointerdown",e=>{this.canvas.setPointerCapture(e.pointerId);start={x:e.offsetX,y:e.offsetY,cx:this.camera.x,cy:this.camera.y};this.wasDrag=false;});this.canvas.addEventListener("pointermove",e=>{if(!start)return;const dx=e.offsetX-start.x,dy=e.offsetY-start.y;if(Math.hypot(dx,dy)>6)this.wasDrag=true;this.camera.x=start.cx+dx;this.camera.y=start.cy+dy;this.draw();});this.canvas.addEventListener("pointerup",e=>{if(!this.wasDrag){const p=this.camera.screenToTile(e.offsetX,e.offsetY,TILE);const u=this.state?.units.find(v=>v.owner==="player"&&v.x===p.x&&v.y===p.y);u?this.onUnit(u.id):this.onTile(p);}start=null;});this.canvas.addEventListener("wheel",e=>{e.preventDefault();this.camera.zoom(e.deltaY<0?1.12:.89,{x:e.offsetX,y:e.offsetY});this.draw();},{passive:false});}
  setState(state){this.state=state;this.draw();}
  draw(){if(!this.state)return;const ctx=this.ctx,rect=this.canvas.getBoundingClientRect(),s=this.camera.scale;ctx.clearRect(0,0,rect.width,rect.height);ctx.save();ctx.translate(this.camera.x,this.camera.y);ctx.scale(s,s);for(const tile of this.state.map.tiles){const x=tile.x*TILE,y=tile.y*TILE;if(tile.revealed){ctx.fillStyle=TERRAIN[tile.terrain].color;ctx.fillRect(x,y,TILE,TILE);ctx.strokeStyle="rgba(240,226,180,.15)";ctx.strokeRect(x+.5,y+.5,TILE-1,TILE-1);if(tile.resource){ctx.fillStyle="#f3ce72";ctx.font="11px sans-serif";ctx.fillText(tile.resource,x+5,y+50);}if(tile.terrain==="forest"){ctx.fillStyle="#173e2f";ctx.font="22px serif";ctx.fillText("♠",x+18,y+34);}if(tile.terrain==="mountains"){ctx.fillStyle="#d2d0c4";ctx.font="22px serif";ctx.fillText("▲",x+17,y+35);}}else{ctx.fillStyle="#101a22";ctx.fillRect(x,y,TILE,TILE);ctx.strokeStyle="#162832";ctx.strokeRect(x+.5,y+.5,TILE-1,TILE-1);}}
    for(const city of this.state.settlements){if(!this.state.map.tiles[indexOf(city.x,city.y,this.state.map.width)].revealed)continue;ctx.fillStyle="#f2d087";ctx.beginPath();ctx.arc((city.x+.5)*TILE,(city.y+.5)*TILE,11,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#392d24";ctx.lineWidth=3;ctx.stroke();}
    for(const u of this.state.units){if(!this.state.map.tiles[indexOf(u.x,u.y,this.state.map.width)].revealed)continue;const selected=u.id===this.state.selectedUnitId;if(selected){ctx.strokeStyle="#ffe8a6";ctx.lineWidth=3;ctx.strokeRect(u.x*TILE+4,u.y*TILE+4,TILE-8,TILE-8);}ctx.fillStyle=u.owner==="player"?"#ecdfbe":"#bd5142";ctx.font="bold 25px sans-serif";ctx.textAlign="center";ctx.fillText(UNIT_TYPES[u.type].icon,(u.x+.5)*TILE,(u.y+.5)*TILE+9);ctx.textAlign="left";}ctx.restore();}
}
